### ISSUE TITLE
Error in vcd vapp info - 'No such child'

### ISSUE THREAD

**Issue by jondwaite** [vmware/vcd-cli#184]
Opening as requested by Paco Gómez.

Trying to show vApp info:
```
C:\<HomeDir> vcd vapp info test01
Usage: vcd vapp info [OPTIONS] <name>

Error: no such child: {http://www.w3.org/2001/XMLSchema-instance}schemaLocation

```
vcd.log for this call shows:
```
Traceback (most recent call last):
 File "<HomeDir>\Python\Python36\site-packages\vcd_cli\vapp.py", line 184, in info
   result = vapp_to_dict(vapp_resource, md, access_control_settings)
 File "<HomeDir>\Python\Python36\site-packages\pyvcloud\vcd\utils.py", line 343, in vapp_to_dict
   result.update(access_control_settings)
 File "src\lxml\objectify.pyx", line 289, in lxml.objectify.ObjectifiedElement.__getitem__ (src\lxml\objectify.c:5172)
 File "src\lxml\objectify.pyx", line 451, in lxml.objectify._lookupChildOrRaise (src\lxml\objectify.c:7228)
AttributeError: no such child: {http://www.w3.org/2001/XMLSchema-instance}schemaLocation
```

vCloud Director version is 8.20.0.2 (API v27.0).

Other commands appear to work fine:
```
C:\<HomeDir>vcd vapp list
isDeployed    isEnabled      memoryAllocationMB  name                     numberOfCpus    numberOfVMs  ownerName    status         storageKB  vdcName
------------  -----------  --------------------  ---------------------  --------------  -------------  -----------  -----------  -----------  ------------
true          true                        12288  test01                             10              5  <user>       POWERED_ON      83886080  <my Vdc>
true          true                        16384  test02                              8              4  <user>       POWERED_ON      41943040  <my Vdc>

C:\<HomeDir>vcd search vapp
id                                    isDeployed    isEnabled      memoryAllocationMB  name                     numberOfCpus    numberOfVMs  ownerName    status         storageKB  vdcName
------------------------------------  ------------  -----------  --------------------  ---------------------  --------------  -------------  -----------  -----------  -----------  ------------
5bbc5273-39e8-4851-835d-fc4f791ef6ea  true          true                        12288  test01                             10              5  <user>       POWERED_ON      83886080  <my Vdc>
4a08defd-3d03-4636-8777-a8308f467448  true          true                        16384  test02                              8              4  <user>       POWERED_ON      41943040  <my Vdc>
```

Anonymised XML dumps for test01 and test02 are attached obtained using:
```
vcd info vapp 5bbc5273-39e8-4851-835d-fc4f791ef6ea > vcd_info_vapp_test01.txt
vcd info vapp 4a08defd-3d03-4636-8777-a8308f467448 > vcd_info_vapp_test02.txt

```
[vcd_info_vapp_test01.txt](https://github.com/vmware/vcd-cli/files/1701359/vcd_info_vapp_test01.txt)
[vcd_info_vapp_test02.txt](https://github.com/vmware/vcd-cli/files/1701360/vcd_info_vapp_test02.txt)

This issue appears to be causing issues for https://github.com/vmware/container-service-extension when attempting to retrieve cluster info. (test01 was a cluster deployed in container-service-extension 0.4.0 and test02 was deployed using container-service-extension 0.4.1)

**Comment by anusuyar** [comment]
@jondwaite Can you run this command and post the output?
vcd vapp acl list  test01

**Comment by jondwaite** [comment]
The acl list shows me as having no access_level (despite being logged in as an Organizational Administrator user):

```
vcd vapp acl list test01
subject_name          subject_type    access_level
--------------------  --------------  --------------
<My OrgName> (org_in_use)  org             None
```

vcd vdc info looks fine (I've substituted the names):

```
vcd vdc info <vdc-name>
property               value
---------------------  ------------------------------------
allocation_model       AllocationVApp
cpu_capacity           0
everyone_access_level  ReadOnly
id                     8bd3ce81-d28d-4d5f-ac2e-3546054b71dc
in_use                 True
is_enabled             True
is_shared_to_everyone  True
mem_capacity           998
name                   <my VDC name>
networks               <List of 3 available VDC networks>
org                    <my Org name>
storage_profiles       <List of 4 available storage profiles in this VDC>
supported_hw           vmx-04
                       vmx-07
                       vmx-08
                       vmx-09
                       vmx-10
                       vmx-11
vapp_templates         <List of vApp templates in this VDC>
vapps                  test01
                       test02
vm_quota               0

```

**Comment by jondwaite** [comment]
Sorry, accidentally closed - reopened.

**Comment by anusuyar** [comment]
> The acl list shows me as having no access_level (despite being logged in as an Organizational Administrator user):

The output just means the VDC it is not shared to all the members of the org.  It corresponds to <IsSharedToEveryone>false</IsSharedToEveryone> in the controlAccess xml.

**Comment by anusuyar** [comment]
I have made a code fix https://github.com/vmware/vcd-cli/commit/010d86cc2ae031f71e0522c72950f19b5b4c74a5 . I think it should fix the issue you were facing. Is it possible for you to test with the latest vcd-cli code?

**Comment by jondwaite** [comment]
Hi anusuyar,

Have updated vapp.py with changes from https://github.com/vmware/vcd-cli/commit/010d86cc2ae031f71e0522c72950f19b5b4c74a5 (and cleared python cache etc.) and still getting the same error / same issue with vcd vapp info <vapp name>. Happy to do more troubleshooting / log collection etc. if required.

**Comment by anusuyar** [comment]
Can you post the error you are getting after applying the patch?

It is better to install the whole package from github directly

> Installation from Local Source Files
> This is the standard installation for development. Clone the code and install from source.
> 
>     $ git clone https://github.com/vmware/vcd-cli.git
>     $ cd vcd-cli
>     $ python3 setup.py develop
> The vcd command will automatically pick up current vcd-cli source files including any changes you have made. Use of virtualenv is recommended to avoid polluting your production Python installation.


Please try the above method and post the errors.
Also if possible post the following REST api results

GET https://<ip>/api/vApp/vapp-d0ea9df2-0bb6-4cc7-8c40-363b0567c74b
GET https://<ip>/api/vApp/vapp-d0ea9df2-0bb6-4cc7-8c40-363b0567c74b/controlAccess

**Comment by jondwaite** [comment]
I thought I had an issue after the patch - I don't - see above.

The original comment I submitted has been edited.

**Comment by anusuyar** [comment]
okay. I will close the issue now.
